const event = $input.first().json.body;
if (!event || event.type !== 'campaign.offer' || !event.event_id) throw new Error('Expected campaign.offer with event_id');
const recipient = event.recipient || {};
const phone = String(recipient.phone || '').replace(/\D/g, '');
if (!/^\d{8,15}$/.test(phone)) throw new Error('Phone must include country code');
if (recipient.sms_marketing_opt_in !== true || recipient.sms_opted_out === true) return [];
const offer = event.offer || {};
const title = String(offer.title || '').trim().slice(0, 100);
const description = String(offer.description || '').trim().slice(0, 260);
const url = String(offer.url || '');
const unsubscribeUrl = String(recipient.unsubscribe_url || '');
if (!title || !description || !/^https:\/\/[^\s]+$/i.test(url) || !/^https:\/\/[^\s]+$/i.test(unsubscribeUrl)) throw new Error('Invalid offer or unsubscribe URL');
return [{json: {event_id: event.event_id, payload: {to: `+${phone}`, message: `${title}: ${description} ${url} Unsubscribe: ${unsubscribeUrl}`}}}];
